on:
  push:
    branches:
      - main
    paths:
      - application/chat-interface/** # Only trigger on changes in this folder
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: rapid-prototype
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: 'actions/checkout@v3'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.WORKLOAD_IDENTITY_POOL_PROVIDER_ID }}'
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - id: 'verify-auth'
        name: 'Verify Authentication'
        run: |
          gcloud auth list
          gcloud projects list
          
      - id: 'upload-artifact'
        name: 'Upload Artifact'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          WORKING_DIR="application/chat-interface"
          cd $WORKING_DIR || { echo "Directory $WORKING_DIR not found."; exit 1; }
          bash publish-build.sh
          bash deploy-to-cloudrun.sh