on:
  push:
    branches:
      - main
    paths:
      - application/test-application/** # Only trigger on changes in this folder
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: rapid-prototype
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: 'actions/checkout@v3'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.WORKLOAD_IDENTITY_POOL_PROVIDER_ID }}'
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      
      - id: 'upload-artifact'
        name: 'Upload Artifact'
        run: |
          WORKING_DIR="application/test-application"
          cd $WORKING_DIR || { echo "Directory $WORKING_DIR not found."; exit 1; }
          bash upload-to-cloud-storage.sh